version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./database:/var/www/database
    networks:
      - laravel
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    command: >
      sh -c "composer install --no-dev --optimize-autoloader &&
             npm install &&
             npm run build &&
             chown -R www-data:www-data /var/www/storage /var/www/database /var/www/bootstrap/cache &&
             chmod -R 775 /var/www/storage /var/www/database /var/www/bootstrap/cache &&
             # Ensure SQLite database file is owned by www-data and writable
             touch /var/www/database/database.sqlite &&
             chown www-data:www-data /var/www/database/database.sqlite &&
             chmod 664 /var/www/database/database.sqlite &&
             php-fpm"

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "2423:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:
    driver: bridge