version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - build_assets:/var/www/public/build
      - ./database:/var/www/database
    networks:
      - laravel
    command: >
      sh -c "composer install &&
             npm install &&
             npm run build &&
             mkdir -p /var/www/database &&
             touch /var/www/database/database.sqlite &&
             chown -R www-data:www-data /var/www/storage /var/www/database /var/www/bootstrap/cache &&
             chmod -R 775 /var/www/storage /var/www/database /var/www/bootstrap/cache &&
             php artisan migrate --force &&
             php-fpm"

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "2423:80"
    volumes:
      - .:/var/www
      - build_assets:/var/www/public/build
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  build_assets: